-- 코드를 입력하세요
SELECT AUTHOR_ID,AUTHOR_NAME,CATEGORY,SUM(SALES*PRICE) AS TOTAL_SALES
FROM (SELECT B.*, A.AUTHOR_NAME
      FROM BOOK B LEFT OUTER JOIN AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID) B
      LEFT JOIN (SELECT *
                FROM BOOK_SALES
                WHERE DATE_FORMAT(SALES_DATE,'%Y-%m') = '2022-01') S
      ON B.BOOK_ID = S.BOOK_ID
GROUP BY B.AUTHOR_ID,B.CATEGORY
ORDER BY 1,3 DESC
;