-- 코드를 입력하세요
WITH TOTAL_SALE AS ( 
    SELECT ONLINE_SALE_ID AS SALE_ID, USER_ID, PRODUCT_ID, SALES_AMOUNT, SALES_DATE
    FROM ONLINE_SALE 
    UNION ALL
    SELECT OFFLINE_SALE_ID AS SALE_ID, NULL, PRODUCT_ID, SALES_AMOUNT, SALES_DATE
    FROM OFFLINE_SALE
)

SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE, 
       PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM TOTAL_SALE
WHERE DATE_FORMAT(SALES_DATE,'%Y-%m') = '2022-03'
ORDER BY SALES_DATE, PRODUCT_ID, USER_ID
;