-- 코드를 입력하세요
WITH AVAILABLE_CAR AS (
    SELECT A.CAR_ID, A.CAR_TYPE, A.DAILY_FEE
    FROM CAR_RENTAL_COMPANY_CAR A
        LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B
        ON A.CAR_ID = B.CAR_ID
        AND (B.START_DATE <= '2022-11-30' AND B.END_DATE >= '2022-11-01')
    WHERE A.CAR_TYPE IN ('세단', 'SUV') -- 세단, SUV 중에
        AND B.CAR_ID IS NULL  -- 대여 기록이 없는 경우
), 
DISCOUNTED_FEE AS (
    SELECT A.CAR_ID, A.CAR_TYPE, 
           FLOOR(A.DAILY_FEE * (1 - B.DISCOUNT_RATE * 0.01) * 30) AS FEE
    FROM AVAILABLE_CAR A
    LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN B
        ON A.CAR_TYPE = B.CAR_TYPE
    WHERE B.DURATION_TYPE = '30일 이상'
)

SELECT CAR_ID, CAR_TYPE, FEE
FROM DISCOUNTED_FEE
WHERE FEE BETWEEN 500000 AND 2000000
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC
;