-- 코드를 입력하세요
SELECT YEAR(B.SALES_DATE) AS YEAR, MONTH(B.SALES_DATE) AS MONTH, 
    A.GENDER, COUNT(DISTINCT A.USER_ID) AS USERS
FROM USER_INFO A 
    LEFT JOIN ONLINE_SALE B 
    ON A.USER_ID = B.USER_ID
WHERE A.GENDER IS NOT NULL AND B.SALES_DATE IS NOT NULL
GROUP BY YEAR, MONTH, A.GENDER
ORDER BY YEAR, MONTH, A.GENDER
;