-- 코드를 작성해주세요
SELECT A.FISH_COUNT, B.FISH_NAME
FROM ( SELECT COUNT(*) AS FISH_COUNT, FISH_TYPE
       FROM FISH_INFO
       GROUP BY FISH_TYPE ) A 
       LEFT JOIN FISH_NAME_INFO B 
       ON A.FISH_TYPE = B.FISH_TYPE
ORDER BY 1 DESC
;