-- 코드를 입력하세요
SELECT P.PRODUCT_CODE, SUM(P.PRICE*O.SALES_AMOUNT) as SALES
FROM PRODUCT P LEFT JOIN OFFLINE_SALE O ON P.PRODUCT_ID = O.PRODUCT_ID
WHERE O.SALES_AMOUNT IS NOT NULL
GROUP BY P.PRODUCT_CODE
ORDER BY 2 DESC, 1;
