-- 코드를 입력하세요
WITH CS_APNT AS (
    SELECT A.PT_NO, A.APNT_YMD, A.APNT_NO, A.MCDP_CD, B.DR_NAME
    FROM APPOINTMENT A INNER JOIN DOCTOR B 
        ON A.MDDR_ID = B.DR_ID
    WHERE A.MCDP_CD = 'CS' AND A.APNT_CNCL_YN = 'N' 
        AND DATE_FORMAT( A.APNT_YMD, '%Y-%m-%d') = '2022-04-13' 
)

SELECT A.APNT_NO, B.PT_NAME, B.PT_NO, A.MCDP_CD, A.DR_NAME, A.APNT_YMD
FROM CS_APNT A INNER JOIN PATIENT B 
    ON A.PT_NO = B.PT_NO
ORDER BY A.APNT_YMD
;