-- 코드를 입력하세요
WITH RECURSIVE HOURS AS (
    SELECT 0 AS HOUR
    UNION ALL 
    SELECT HOUR + 1
    FROM HOURS
    WHERE HOUR < 23
)

SELECT A.HOUR, COUNT(B.ANIMAL_ID) AS COUNT
FROM HOURS A 
    LEFT JOIN ANIMAL_OUTS B ON A.HOUR = HOUR(B.DATETIME)
GROUP BY A.HOUR
;