-- 코드를 입력하세요 
SELECT MEMBER_NAME,REVIEW_TEXT,DATE_FORMAT(REVIEW_DATE,'%Y-%m-%d') as REVIEW_DATE
FROM MEMBER_PROFILE M LEFT JOIN REST_REVIEW R ON M.MEMBER_ID = R.MEMBER_ID
WHERE M.MEMBER_ID = (SELECT A.MEMBER_ID
                        FROM REST_REVIEW A
                        GROUP BY A.MEMBER_ID
                        ORDER BY COUNT(*) DESC
                        LIMIT 1)
ORDER BY 3,2