-- 코드를 작성해주세요
SELECT B.YEAR, B.MAX_VALUE - A.SIZE_OF_COLONY AS YEAR_DEV, A.ID
FROM ECOLI_DATA A LEFT JOIN (
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX_VALUE
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
) B ON YEAR(A.DIFFERENTIATION_DATE) = B.YEAR
ORDER BY YEAR, YEAR_DEV
;