-- 코드를 작성해주세요
SELECT FA.ID, FB.FISH_NAME, FA.LENGTH
FROM FISH_INFO FA
    LEFT JOIN (
        SELECT A.FISH_TYPE, B.FISH_NAME, MAX(LENGTH) AS MLEN
        FROM FISH_INFO A 
            INNER JOIN FISH_NAME_INFO B
            ON A.FISH_TYPE = B.FISH_TYPE
        GROUP BY A.FISH_TYPE, B.FISH_NAME
    ) FB
    ON FA.FISH_TYPE = FB.FISH_TYPE
WHERE FA.LENGTH = FB.MLEN
ORDER BY FA.ID
;